Profile:
  defaultRank: 100        # начальный ранг нового профиля
  ageRestriction: 14      # минимальный возраст для регистрации
  notRealAge: 100         # техническое ограничение (защита от нереальных значений)
  findAgeRange: 2         # разброс возраста при поиске (± значение)
  minBioLength: 10        # минимальная длина описания профиля
  maxBioLength: 200       # максимальная длина описания профиля
  maxNameLength: 30       # максимальная длина имени
  maxNumMedia: 5          # максимальное количество медиа в профиле

Match:
  recentMatchDays: 7      # ограничение на частые повторы лайков (анти‑спам)

Languages:
  ru: Русский             # доступные языки и их подписи в интерфейсе
  en: English