"""update

Revision ID: 67642903d0b9
Revises: b49d42ce00c1
Create Date: 2025-08-19 00:57:29.506160

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "67642903d0b9"
down_revision: Union[str, Sequence[str], None] = "b49d42ce00c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "is_active", sa.Boolean(), server_default=text("true"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "is_active")
    # ### end Alembic commands ###
