"""update

Revision ID: c245cd6e14d7
Revises: 9a907f327a66
Create Date: 2025-08-16 17:29:51.981507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c245cd6e14d7'
down_revision: Union[str, Sequence[str], None] = '9a907f327a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('rank_cursor', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('profile_cursor', sa.BigInteger(), nullable=True))
    op.alter_column('profiles', 'rank',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_column('profiles', 'cursor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('cursor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('profiles', 'rank',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('profiles', 'profile_cursor')
    op.drop_column('profiles', 'rank_cursor')
    # ### end Alembic commands ###
