"""update

Revision ID: b49d42ce00c1
Revises: 943257158b11
Create Date: 2025-08-19 00:36:14.604358

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b49d42ce00c1"
down_revision: Union[str, Sequence[str], None] = "943257158b11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("from_profile_id", sa.BigInteger(), nullable=False),
        sa.Column("to_profile_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("WAITING_ACTION", "REJECTED", "MATCHED", name="status"),
            nullable=False,
        ),
        sa.Column("message_text", sa.String(), nullable=True),
        sa.Column("message_video_file_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_profile_id"], ["profiles.user_id"], ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(
            ["to_profile_id"], ["profiles.user_id"], ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("matches")
    # ### end Alembic commands ###
