"""update

Revision ID: 943257158b11
Revises: c245cd6e14d7
Create Date: 2025-08-16 18:10:47.184554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '943257158b11'
down_revision: Union[str, Sequence[str], None] = 'c245cd6e14d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), server_default=text("'[]'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'media')
    # ### end Alembic commands ###
